<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Vite Manifest Path
    |--------------------------------------------------------------------------
    |
    | This value determines the path to the Vite "manifest.json" file. You
    | should ensure that this value is correct and points to the location
    | of the manifest generated by Vite during the build process.
    |
    */

    'manifest_path' => public_path('build/manifest.json'),

    /*
    |--------------------------------------------------------------------------
    | Vite Dev Server Hot File
    |--------------------------------------------------------------------------
    |
    | This value determines the path to the Vite "hot" file, which indicates
    | that the Vite development server is running. This file is used to
    | dynamically switch between development and production assets.
    |
    */

    'hot_file' => public_path('hot'),

    /*
    |--------------------------------------------------------------------------
    | Vite Build Directory
    |--------------------------------------------------------------------------
    |
    | This value determines the build directory for your compiled assets.
    | Typically, this directory is located within the "public" directory
    | and contains the compiled assets from your Vite build process.
    |
    */

    'build_path' => 'build',

];
